# Generated by Django 4.1.5 on 2023-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_order_session_order_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('completed', 'Завершенный')], default='new', max_length=100, verbose_name='Status'),
        ),
    ]
