# Generated by Django 4.1.5 on 2023-01-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_order_products_alter_orderproduct_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
